<?php
/**
 * This file is part of Japanese Consumption Tax Extension For Magento2 the project.
 *
 * Copyright (c) 2023 Adobe (or other copyright holders)
 *
 * For the full copyright and license information, please view the OSL-3.0
 * license that is bundled with this source code in the file LICENSE, or
 * at https://opensource.org/licenses/OSL-3.0
 */
/** @var Magentoj\JapaneseConsumptionTax\Block\Order\Jct $block */
?>

<?php foreach ($block->getTotals() as $_code => $_total): ?>
    <tr class="<?= $block->escapeHtmlAttr($_code) ?>">
        <th <?= /* @noEscape */ $block->getLabelProperties() ?> scope="row">
            <?= $block->escapeHtml($_total->getLabel()) ?>
        </th>
        <td <?= /* @noEscape */ $block->getValueProperties() ?>>
            <?php if ($_total->getIsTax() && $_total->getIsIncluded()): ?>
                <?= /* @noEscape */ "(" . $block->formatValue($_total) . ")" ?>
            <?php else: ?>
                <?= /* @noEscape */ $block->formatValue($_total) ?>
            <?php endif; ?>
        </td>
    </tr>
<?php endforeach; ?>
