<?php
/** @var Magentoj\JapaneseConsumptionTax\Block\Order\Jct $block */
?>

<?php foreach ($block->getTotals() as $_code => $_total): ?>
    <tr class="<?= $block->escapeHtmlAttr($_code) ?>">
        <th <?= /* @noEscape */ $block->getLabelProperties() ?> scope="row">
            <?= $block->escapeHtml($_total->getLabel()) ?>
        </th>
        <td <?= /* @noEscape */ $block->getValueProperties() ?>>
            <?php if ($_total->getIsTax() && $_total->getIsIncluded()): ?>
                <?= /* @noEscape */ "(" . $block->formatValue($_total) . ")" ?>
            <?php else: ?>
                <?= /* @noEscape */ $block->formatValue($_total) ?>
            <?php endif; ?>
        </td>
    </tr>
<?php endforeach; ?>
