<?php
/** @var $block Japan\Tax\Block\Sales\Order\Jct */

/** @var \Magento\Tax\Helper\Data $taxHelper */
$taxHelper = $block->getData('taxHelper');
?>

<?php foreach ($block->getTotals() as $_code => $_total) : ?>
    <tr class="<?= $block->escapeHtmlAttr($_code) ?>">
        <th <?= /* @noEscape */ $block->getLabelProperties() ?> scope="row">
            <?= $block->escapeHtml($_total->getLabel()) ?>
        </th>
        <td <?= /* @noEscape */ $block->getValueProperties() ?>>
            <?php if ($_total->getIsTax() && $taxHelper->priceIncludesTax()) : ?>
                <?= /* @noEscape */ "(" . $block->formatValue($_total) . ")" ?>
            <?php else : ?>
                <?= /* @noEscape */ $block->formatValue($_total) ?>
            <?php endif; ?>
        </td>
    </tr>
<?php endforeach; ?>
