<?php
/**
 * This file is part of the Japanese Consumption Tax Extension For Magento2 project.
 *
 * Copyright (c) 2023 Adobe (or other copyright holders)
 *
 * For the full copyright and license information, please view the OSL-3.0
 * license that is bundled with this source code in the file LICENSE, or
 * at https://opensource.org/licenses/OSL-3.0
 */
/** @var Magentoj\JapaneseConsumptionTax\Block\Order\StoreInfo $block */
?>
<div class="block block-store-info-view">
    <div class="block-content">
        <div class="box box-store-address">
            <div class="box-content">
                <?= $block->getAddress() ?>
                <div class="registration-number">
                    <?= $block->escapeHtml(__('Registration # ')) . trim($block->getRegistrationNumber()) ?>
                </div>
            </div>
        </div>
    </div>
</div>
